### ISSUE TITLE
ModuleNotFoundError: No module named 'dyhead._C'

### ISSUE THREAD

**Issue by yaofanji** [microsoft/DynamicHead#42]
Thanks for sharing your great work!But I encountered this error for a long time and can't solve it.
`Traceback (most recent call last):
  File "train_net.py", line 33, in <module>
    from dyhead import add_dyhead_config
  File "/user-data/DynamicHead-master/dyhead/__init__.py", line 2, in <module>
    from .dyhead import DyHead
  File "/user-data/DynamicHead-master/dyhead/dyhead.py", line 7, in <module>
    from .deform import ModulatedDeformConv
  File "/user-data/DynamicHead-master/dyhead/deform.py", line 8, in <module>
    import dyhead._C as _C
ModuleNotFoundError: No module named 'dyhead._C'`

**Comment by MangoFF** [comment]
ME too！
